Adding Sort by Mesh Sorting Order
JLChnToZ/SkinnedMeshCombiner pull request #3
Opened 2024-03-14 15:05 UTC by SlowFeather

When merging Spine baked bones, it is necessary to correctly sort the Mesh, otherwise the rendering order will be disordered.

2024-03-14 19:47 UTC, JLChnToZ commented
Thank you for opening a pull request. But I see there's many lines are just rearranges the braces position, I hope you don't mess with the formatting when requesting to merge.

2024-03-14 19:52 UTC, JLChnToZ requested changes
Please don't mess with formatting, just change where related to the feature.

2024-03-15 02:26 UTC, SlowFeather commented
I'm sorry it was my negligence, I corrected it.

2024-03-15 03:28 UTC, JLChnToZ approved these changes

2024-03-15 03:28 UTC, merged